[package]
name = "catus"
version = "0.1.0"
edition = "2024"

[dependencies]
alacritty_terminal = "0.25.1"
anyhow = "1"
async-trait = "0.1.89"
dashmap = "6.1.0"
dirs = "6"
gpui = "0.2.2"
gpui-component = "0.5.1"
# Optional, for default bundled assets
gpui-component-assets = "0.5.1"
hashbrown = "0.15"
russh = "0.57.0"
russh-sftp = "2.1.1"
