[package]
name = "catus"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
gpui = "0.2.2"
gpui-component = "0.5.1"
# Optional, for default bundled assets
gpui-component-assets = "0.5.1"
